// <auto-generated />
using System;
using Companions.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Companions.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ActivityBuddy", b =>
                {
                    b.Property<string>("ActivitiesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuddiesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ActivitiesId", "BuddiesId");

                    b.HasIndex("BuddiesId");

                    b.ToTable("ActivityBuddy");
                });

            modelBuilder.Entity("AppointmentAppointmentType", b =>
                {
                    b.Property<string>("AppointmentTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppointmentsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AppointmentTypeId", "AppointmentsId");

                    b.HasIndex("AppointmentsId");

                    b.ToTable("AppointmentAppointmentType");
                });

            modelBuilder.Entity("Companions.API.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Companions.API.Models.Activity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActivityTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Companions.API.Models.ActivityType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("Companions.API.Models.Appointment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AppoinmentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BuddyId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BuddyId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Companions.API.Models.AppointmentType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppointmentTypes");
                });

            modelBuilder.Entity("Companions.API.Models.Buddy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpeciesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Buddies");
                });

            modelBuilder.Entity("Companions.API.Models.BuddyWeight", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuddyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateWeighed")
                        .HasColumnType("datetime2");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BuddyId");

                    b.ToTable("BuddyWeights");
                });

            modelBuilder.Entity("Companions.API.Models.FeedBrand", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FeedBrands");
                });

            modelBuilder.Entity("Companions.API.Models.FeedingSchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("BuddyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FeedProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TimeOfDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuddyId");

                    b.HasIndex("FeedProductId");

                    b.ToTable("FeedingSchedules");
                });

            modelBuilder.Entity("Companions.API.Models.FeedProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FeedBrandId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FeedBrandId");

                    b.ToTable("FeedProducts");
                });

            modelBuilder.Entity("Companions.API.Models.Species", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpeciesRace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("Companions.API.Models.Vaccination", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("AmountOfRepeats")
                        .HasColumnType("tinyint");

                    b.Property<string>("BuddyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateFirstVaccination")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuddyId");

                    b.ToTable("Vaccinations");
                });

            modelBuilder.Entity("ActivityBuddy", b =>
                {
                    b.HasOne("Companions.API.Models.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Companions.API.Models.Buddy", null)
                        .WithMany()
                        .HasForeignKey("BuddiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppointmentAppointmentType", b =>
                {
                    b.HasOne("Companions.API.Models.AppointmentType", null)
                        .WithMany()
                        .HasForeignKey("AppointmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Companions.API.Models.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Companions.API.Models.Activity", b =>
                {
                    b.HasOne("Companions.API.Models.ActivityType", "ActivityType")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityTypeId");

                    b.Navigation("ActivityType");
                });

            modelBuilder.Entity("Companions.API.Models.Appointment", b =>
                {
                    b.HasOne("Companions.API.Models.Buddy", null)
                        .WithMany("Appointments")
                        .HasForeignKey("BuddyId");
                });

            modelBuilder.Entity("Companions.API.Models.Buddy", b =>
                {
                    b.HasOne("Companions.API.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Companions.API.Models.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId");

                    b.Navigation("Account");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Companions.API.Models.BuddyWeight", b =>
                {
                    b.HasOne("Companions.API.Models.Buddy", "Buddy")
                        .WithMany("BuddyWeights")
                        .HasForeignKey("BuddyId");

                    b.Navigation("Buddy");
                });

            modelBuilder.Entity("Companions.API.Models.FeedingSchedule", b =>
                {
                    b.HasOne("Companions.API.Models.Buddy", "Buddy")
                        .WithMany("FeedingSchedules")
                        .HasForeignKey("BuddyId");

                    b.HasOne("Companions.API.Models.FeedProduct", "FeedProduct")
                        .WithMany()
                        .HasForeignKey("FeedProductId");

                    b.Navigation("Buddy");

                    b.Navigation("FeedProduct");
                });

            modelBuilder.Entity("Companions.API.Models.FeedProduct", b =>
                {
                    b.HasOne("Companions.API.Models.FeedBrand", "FeedBrand")
                        .WithMany("FeedProducts")
                        .HasForeignKey("FeedBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedBrand");
                });

            modelBuilder.Entity("Companions.API.Models.Vaccination", b =>
                {
                    b.HasOne("Companions.API.Models.Buddy", "Buddy")
                        .WithMany("Vaccinations")
                        .HasForeignKey("BuddyId");

                    b.Navigation("Buddy");
                });

            modelBuilder.Entity("Companions.API.Models.ActivityType", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Companions.API.Models.Buddy", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BuddyWeights");

                    b.Navigation("FeedingSchedules");

                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("Companions.API.Models.FeedBrand", b =>
                {
                    b.Navigation("FeedProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
